### ISSUE TITLE
Unexpected error traceback is printed between progress logs

### ISSUE THREAD

**Issue by kangasta** [kangasta/yaml_requests#54]
This happens in environments where stdout and stderr are outputted to same target. This is the case for example when running the plan inside Docker containers.

Example plan to reproduce:

```yaml
requests:
- post:
    url: http://localhost:5000/upload
    files:
      json:
        animal: "{{ lookup('file', 'animal.txt') }}"
```

Example command:

```sh
yaml_requests tst/plans/open_file_not_found.yml &> out
```
