### ISSUE TITLE
Print nicer error message on `FileNotFound` error raised by `open` or `lookup`

### ISSUE THREAD

**Issue by kangasta** [kangasta/yaml_requests#56]
If file is not found from the path defined by the user, the result should be validation error or runtime error instead of an unknown error.

File to reproduce current error:

```yaml
requests:
- post:
    url: http://localhost:5000/upload
    files:
      photo: "{{ open('tst/data/photo.jpg', 'rb') }}"
```
